# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e66332bf6435a86897a4e1c93f8ee00d"
name = "HidePayment"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_payment_customizations,read_payment_customizations,read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
