query RunInput($tags_list: [String!]! = [], $collection_ids: [ID!]! = []) {
  cart {
    cost {
      totalAmount {
        amount
      }
      subtotalAmount {
        amount
      }
    }
    buyerIdentity {
      customer {
        hasTags(tags: $tags_list) {
          hasTag
          tag
        }
      }
    }
    deliveryGroups {
      deliveryAddress {
        countryCode
        provinceCode
        zip
        city
        address1
      }
      selectedDeliveryOption {
        handle
        title
        code
        deliveryMethodType
      }
    }
    lines {
      quantity
      merchandise {
        ... on ProductVariant {
          sku
          weight
          weightUnit
          product {
            id
            inCollections(ids: $collection_ids) {
              collectionId
              isMember
            }
          }
        }
      }
    }
  }
  paymentMethods {
    id
    name
  }
  paymentCustomization {
    metafield(namespace: "$app:payment-rules", key: "function-configuration") {
      value
    }
  }
}
